### ISSUE TITLE
How to integrate into another C++ file. 

### ISSUE THREAD

**Issue by kevinlinxc** [FrotBot/SwitchProConLinuxUSB#30]
Question: if I want to integrate this controller into running from another c++ file, what do I need to do. Is the procon_driver executable standalone, meaning I would just have to figure out how to run an executable from C++? Or does it depend on other things in the repo, meaning I'd have to do other stuff.

**Comment by TheWaveWarden** [comment]
Yes this is a standalone application.

If you want to integrate the code into your application just check the `main.cpp` file from the repo. There's a lot of boiler plate code for the command line options. The actual usage of the ProController starts here:

https://github.com/TheWaveWarden/SwitchProConLinuxUSB/blob/a436c45671379657a354666c232a368e8072bb57/main.cpp#L144

**Comment by TheWaveWarden** [comment]
Closing since this is not an issue
