### ISSUE TITLE
No controller found...

### ISSUE THREAD

**Issue by kevinlinxc** [FrotBot/SwitchProConLinuxUSB#33]
This package used to be working for me, and I could use my Pro Controller effectively.
I came back to my work recently, and every time i run ./procon_driver, it gives me the error  "No controller found...". I thought it could have been caused by software updates, so I started a fresh install of Ubuntu 18.04 LTS, cloned this repo, but I have the same problem. 

Just to be sure, should the controller be connected by USB, bluetooth, or both? I would assume USB only given the name of the package, but I remember it working with a few different setups. Also, should the controller appear in evtest when it is ready to be controlled by the driver?

**Comment by kevinlinxc** [comment]
@TheWaveWarden

**Comment by TheWaveWarden** [comment]
@kevinlinxc The driver is only USB. Furthermore, connecting it via Bluetooth (even to your Switch) might interfere with the USB connection. Make sure it is not connected to anything before you start the program.

Have you tried running the program with `sudo ./procon_driver`?

When running `evtest` before running the driver, it should appear as:
```
/dev/input/event2:	Nintendo Co., Ltd. Pro Controller
```
After you started the program, it should appear as
```
/dev/input/event2:	Switch ProController disguised as XBox360
```

**Comment by kevinlinxc** [comment]
@TheWaveWarden When I run evtest before running the driver, I don't see anything, unless I have Bluetooth on. It seems my USB cable connection isn't working then.  Do you know what I can do to make it work? I've tried sudo but since it's not even showing up in evtest I'm pretty sure that's the issue.

**Comment by TheWaveWarden** [comment]
@kevinlinxc hmmm that's weird. Does it work with your switch when using USB? I think you can see in the menu somewhere whether it is connected via USB / BT right now.

Also: I assume you're using an official Nintendo ProController, not a third party one?

In any case: This project depends on the controller being found beforehand with evtest.

**Comment by kevinlinxc** [comment]
@TheWaveWarden  It is an official Nintendo ProController, I bought it to control a robot so I don't have an actual Switch. It works with Windows+Steam when I plug it into my computer, but when I'm on Ubuntu 18.04 I don't see it on evtest or lsusb. I'll keep looking for a solution to this, let me know if you have any ideas.

**Comment by TheWaveWarden** [comment]
@kevinlinxc you have steam installed and running on the same machine?

This might be the problem, the steam client probaby does something similar as this project. Try rebooting your system without opening steam if this is the case.

**Comment by TheWaveWarden** [comment]
@kevinlinxc I'm going to close this issue for now

**Comment by kevinlinxc** [comment]
No, steam is installed on a Windows PC, Ubuntu was installed on a laptop. The fix was to switch the USB that had my Ubuntu image with the USB that connected the controller. Only one of the USB ports worked for the controller for some reason, even though both worked for booting into Ubuntu.

**Comment by roracle** [comment]
How can this be closed? I have the exact same problem.

evtest output (including face button input):
`No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event6:	Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller
Select the device event number [0-6]: 6
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x20d6 product 0xa711 version 0x111
Input device name: "Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 306 (BTN_C)
    Event code 307 (BTN_NORTH)
    Event code 308 (BTN_WEST)
    Event code 309 (BTN_Z)
    Event code 310 (BTN_TL)
    Event code 311 (BTN_TR)
    Event code 312 (BTN_TL2)
    Event code 313 (BTN_TR2)
    Event code 314 (BTN_SELECT)
    Event code 315 (BTN_START)
    Event code 316 (BTN_MODE)
    Event code 317 (BTN_THUMBL)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 1 (ABS_Y)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 2 (ABS_Z)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 5 (ABS_RZ)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1613778033.128481, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90002
Event: time 1613778033.128481, type 1 (EV_KEY), code 305 (BTN_EAST), value 1
Event: time 1613778033.128481, -------------- SYN_REPORT ------------
Event: time 1613778033.320474, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90002
Event: time 1613778033.320474, type 1 (EV_KEY), code 305 (BTN_EAST), value 0
Event: time 1613778033.320474, -------------- SYN_REPORT ------------
Event: time 1613778035.016497, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1613778035.016497, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 1
Event: time 1613778035.016497, -------------- SYN_REPORT ------------
Event: time 1613778035.224498, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1613778035.224498, type 1 (EV_KEY), code 304 (BTN_SOUTH), value 0
Event: time 1613778035.224498, -------------- SYN_REPORT ------------
Event: time 1613778035.792587, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1613778035.792587, type 1 (EV_KEY), code 307 (BTN_NORTH), value 1
Event: time 1613778035.792587, -------------- SYN_REPORT ------------
Event: time 1613778035.936510, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1613778035.936510, type 1 (EV_KEY), code 307 (BTN_NORTH), value 0
Event: time 1613778035.936510, -------------- SYN_REPORT ------------
Event: time 1613778036.352526, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90003
Event: time 1613778036.352526, type 1 (EV_KEY), code 306 (BTN_C), value 1
Event: time 1613778036.352526, -------------- SYN_REPORT ------------
Event: time 1613778036.504567, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90003
Event: time 1613778036.504567, type 1 (EV_KEY), code 306 (BTN_C), value 0
Event: time 1613778036.504567, -------------- SYN_REPORT ------------`

Running ./procon_driver
`--------------------------------------------------------------------------
| Nintendo Switch Pro-Controller USB uinput driver. Version: 1.0 alpha2  |
--------------------------------------------------------------------------

No controller found...
`

**Comment by roracle** [comment]
Reminder: my computer is 100% Pop OS 20.04.  There is no Windows anything installed on my system.  I'm so sick of my games and Steam not recognizing my controller.

**Comment by kevinlinxc** [comment]
Switching USB ports and running sudo ./procon_driver was my fix, have you tried those?

**Comment by roracle** [comment]
> Switching USB ports and running sudo ./procon_driver was my fix, have you tried those?

I cannot do this. For some reason, if my 2.0 slots are used by anything other than my speakers or keyboard/mouse wireless adapter it makes my entire system crawl until it's unresponsive.

It's beneficial because I can use the 3.0 slot for anything at all, including the speaker and adapter, but there's only one of those.

**Comment by TheWaveWarden** [comment]
@roracle the basis for this project is that your OS will detect the controller like described above. If this is not the case the controller will not work. You have to make it to this point before using this project.

That being said: Your evtest output says:
`Not running as root, no devices may be available`
Did you try running evtest with sudo?

Also maybe PopOS handles devices out of the box differently than Ubuntu.

Also: If you're playing games via Steam, you don't even need to use this project. Steam has built in support for the ProController, which is probably ten times as robust as my solution. Check here:
https://uk.pcmag.com/nintendo-switch-2/117052/how-to-use-a-nintendo-switch-pro-controller-on-a-pc

The guide is for Windows, but the steps are exactly the same once you get to the Steam part if I recall right.

**Comment by roracle** [comment]
Yeah that's the strange thing. Pop is extremely focused on ensuring everything just works, but if Steam is set up to use Nintendo's controller, it still doesn't detect it.

Pop is pretty much the exact same as Ubuntu in most respects. The controller I'm using is a Nintendo Switch Pro controller, and it's the one with the Zelda designs on it. I do not know if that changes anything.

You see, it's not meant to be a wired controller, but the USB cord used to charge it allows it to work as such. If this isn't normally how the controller should work, then that might be the problem.

**Comment by TheWaveWarden** [comment]
@roracle can you please post a picture of you controller? I can't find any **official** Nintendo Pro Controller which features such design, only ones by Hori.

This project will not work with anything but a controller by Nintendo (I think the same is true for the Steam driver)

**Comment by roracle** [comment]
> @roracle can you please post a picture of you controller? I can't find any **official** Nintendo Pro Controller which features such design, only ones by Hori.
> 
> This project will not work with anything but a controller by Nintendo (I think the same is true for the Steam driver)

It's the Power A controller, I just found out. But it's only wired, no wireless option from what I'm seeing.

Mind you, this is my nephew's, I didn't realize it wasn't official. However, it still identifies as a supported controller with the same pid and whatever that other number is (I'm still in wake up mode, forgive me).

Basically, there's no reason it shouldn't be working if it is meant to work.![20210220_075221.jpg](https://user-images.githubusercontent.com/9681146/108597870-d1d66a00-7350-11eb-9057-c8bb2697a82f.jpg)

**Comment by TheWaveWarden** [comment]
> Basically, there's no reason it shouldn't be working if it is meant to work.

Yes, there are these two lines:
https://github.com/TheWaveWarden/SwitchProConLinuxUSB/blob/a436c45671379657a354666c232a368e8072bb57/src/procon.hpp#L34-L35

They specify the manufacturer ID of Nintendo, as well as the Product ID of the ProController. You might be able to find out the Manufacturer ID and product code of your controller via evtest. And it **might** work then, I can not guarantee it. Perhaps there is another way to find the IDs, it's been a long time since I did this.

**Comment by TheWaveWarden** [comment]
> vendor 0x20d6 product 0xa711

Ah I just went through the evtest output you posted. Try to give these two values a shot!

**Comment by roracle** [comment]
> > vendor 0x20d6 product 0xa711
> 
> Ah I just went through the evtest output you posted. Try to give these two values a shot!

That's what I was talking about, the pid and the other I couldn't remember. They're the same as listed here:
https://support.steampowered.com/kb/5199-TOKV-4426/supported-controller-database

**Comment by TheWaveWarden** [comment]
What do you mean they're the same? They're different from the Nintendo ones at least. Did you try exchanging the values and rebuilding?

**Comment by roracle** [comment]
> What do you mean they're the same? They're different from the Nintendo ones at least. Did you try exchanging the values and rebuilding?

Oh, no, I just meant if Steam by default says it's supported, I don't see why I would have to do any of this to begin with.

But I'll give it a shot later and get back to you.

**Comment by roracle** [comment]
Nope, still doesn't work. Did I put the info in the proper lines?![20210220_110809.jpg](https://user-images.githubusercontent.com/9681146/108603165-f4c24780-736b-11eb-9e1c-87b65b4f5b10.jpg)

**Comment by TheWaveWarden** [comment]
@roracle no you mixed them up. Try this:
```cpp
#define PROCON_ID 0xa711
#define NINTENDO_ID 0x20d6
```

**Comment by roracle** [comment]
> @roracle no you mixed them up. Try this:
> ```cpp
> #define PROCON_ID 0xa711
> #define NINTENDO_ID 0x20d6
> ```

Well I'm getting this, more than before I guess![20210220_113723.jpg](https://user-images.githubusercontent.com/9681146/108603888-0dccf780-7370-11eb-8977-1fb36a98a21b.jpg)

**Comment by TheWaveWarden** [comment]
Ok then my best guess is that the communication of the controllers works differently. You're on your own from here, sorry. The line that fails is this one:

https://github.com/TheWaveWarden/SwitchProConLinuxUSB/blob/a436c45671379657a354666c232a368e8072bb57/src/procon.hpp#L319

In case you want to dive in and try to figure it out yourself.
